// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CNPM.Migrations
{
    [DbContext(typeof(MainContext))]
    [Migration("20250424152632_new")]
    partial class @new
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cnpm.Models.Object.Admin", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("Cnpm.Models.Object.DayHoc", b =>
                {
                    b.Property<int>("IdGiaSu")
                        .HasColumnType("int");

                    b.Property<int>("IdKhoaHoc")
                        .HasColumnType("int");

                    b.ToTable("DayHoc");
                });

            modelBuilder.Entity("Cnpm.Models.Object.GiaSu", b =>
                {
                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("KhuVuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.ToTable("GiaSu");
                });

            modelBuilder.Entity("Cnpm.Models.Object.HocVien", b =>
                {
                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("KhoiLop")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.ToTable("HocVien");
                });

            modelBuilder.Entity("Cnpm.Models.Object.HopDong", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("IdGiaSu")
                        .HasColumnType("int");

                    b.Property<int>("IdHocVien")
                        .HasColumnType("int");

                    b.Property<int>("IdKhoaHoc")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.ToTable("HopDong");
                });

            modelBuilder.Entity("Cnpm.Models.Object.IdCounter", b =>
                {
                    b.Property<int>("CurrentId")
                        .HasColumnType("int");

                    b.Property<string>("TableName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.ToTable("IdCounter");
                });

            modelBuilder.Entity("Cnpm.Models.Object.KhoaHoc", b =>
                {
                    b.Property<int>("HocPhi")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("KhoiLop")
                        .HasColumnType("int");

                    b.Property<int>("SoBuoi")
                        .HasColumnType("int");

                    b.Property<string>("TenKhoaHoc")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("TenMonHoc")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.ToTable("KhoaHoc");
                });

            modelBuilder.Entity("Cnpm.Models.Object.TGBGiaSu", b =>
                {
                    b.Property<int>("IdGiaSu")
                        .HasColumnType("int");

                    b.Property<DateTime>("TDiemBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TDiemKetThuc")
                        .HasColumnType("datetime2");

                    b.ToTable("TGBGiaSu");
                });

            modelBuilder.Entity("Cnpm.Models.Object.TGBHocVien", b =>
                {
                    b.Property<int>("IdHocVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("TDiemBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TDiemKetThuc")
                        .HasColumnType("datetime2");

                    b.ToTable("TGBHocVien");
                });

            modelBuilder.Entity("Cnpm.Models.Object.TGBHopDong", b =>
                {
                    b.Property<int>("IdHopDong")
                        .HasColumnType("int");

                    b.Property<DateTime>("TDiemBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TDiemKetThuc")
                        .HasColumnType("datetime2");

                    b.ToTable("TGBHopDong");
                });
#pragma warning restore 612, 618
        }
    }
}
